"""Peripheral Simulation Generator for Ignition Gateway Fleet.

Generates Docker Compose stacks and helper artifacts to simulate production OT/IT
ecosystems around the Ignition fleet without modifying the gateway backups:
- PostgreSQL / TimescaleDB pre-populated with discovered databases, users, and historian tables
- Mailpit SMTP container for alarm notifications
- Mosquitto MQTT broker for Sparkplug B and Cirrus Link modules
- Mock OPC-UA & Rockwell CIP / PLC socket responder
- Network aliases matching all discovered production hostnames
"""

import os
from pathlib import Path
from typing import Any, Dict, List, Optional, Set, Tuple
import yaml

from ignition_gateway_harness.backup_analyzer import FleetAnalysisReport
from ignition_gateway_harness.compose_builder import CleanYamlDumper, format_relative_path
from ignition_gateway_harness.models import GatewayServiceConfig


def generate_init_sql(report: FleetAnalysisReport) -> str:
    """Generate SQL initialization script for PostgreSQL / TimescaleDB based on discovered backups."""
    sql_lines = [
        "-- Auto-generated by Ignition Gateway Harness Peripheral Simulator",
        "-- Source of truth: Discovered databases and users from gateway backups",
        "",
    ]

    # Discovered databases
    databases: Set[str] = set()
    for db_set in report.database_targets.values():
        databases.update(db_set)

    # Standard fallback databases if none discovered
    default_dbs = {"mes", "scada", "prod", "ignition"}
    databases.update(default_dbs)

    for db_name in sorted(databases):
        clean_db = db_name.lower().replace("-", "_").strip()
        if clean_db and clean_db != "postgres" and clean_db != "template1":
            sql_lines.append(f"SELECT 'CREATE DATABASE {clean_db}' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '{clean_db}')\\gexec")

    # Discovered users
    users: Set[str] = set()
    for ga in report.gateways.values():
        for db in ga.databases:
            if db.username:
                users.add(db.username.lower())

    if not users:
        users = {"ignition", "defsvcmesdev", "defsvcscadadev", "defsvcprdheadprd"}

    user_list_sql = ", ".join(f"'{u}'" for u in sorted(users))
    sql_lines.extend([
        "",
        "-- Discovered user accounts with full privileges across simulated databases",
        "DO $$",
        "DECLARE",
        "    u text;",
        "BEGIN",
        f"    FOR u IN (SELECT unnest(ARRAY[{user_list_sql}]))",
        "    LOOP",
        "        IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = u) THEN",
        "            EXECUTE format('CREATE USER %I WITH PASSWORD %L SUPERUSER CREATEDB', u, 'password');",
        "        END IF;",
        "    END LOOP;",
        "END $$;",
        "",
        "-- Standard Ignition Historian and Alarm Journal tables in default ignition DB",
        "\\c ignition;",
        "",
        "CREATE TABLE IF NOT EXISTS sqlth_drv (",
        "    id SERIAL PRIMARY KEY,",
        "    name VARCHAR(255) NOT NULL UNIQUE",
        ");",
        "INSERT INTO sqlth_drv (name) VALUES ('default') ON CONFLICT DO NOTHING;",
        "",
        "CREATE TABLE IF NOT EXISTS sqlth_tables (",
        "    id SERIAL PRIMARY KEY,",
        "    tablename VARCHAR(255) NOT NULL UNIQUE,",
        "    drvid INT REFERENCES sqlth_drv(id)",
        ");",
        "",
        "CREATE TABLE IF NOT EXISTS sqlth_te (",
        "    id SERIAL PRIMARY KEY,",
        "    tagid VARCHAR(500) NOT NULL UNIQUE,",
        "    datatype INT NOT NULL,",
        "    querymode INT NOT NULL",
        ");",
        "",
        "CREATE TABLE IF NOT EXISTS sqlth_sce (",
        "    id SERIAL PRIMARY KEY,",
        "    scid INT NOT NULL,",
        "    start_time BIGINT NOT NULL,",
        "    end_time BIGINT",
        ");",
        "",
        "CREATE TABLE IF NOT EXISTS alarm_events (",
        "    id SERIAL PRIMARY KEY,",
        "    eventid VARCHAR(255) NOT NULL,",
        "    source VARCHAR(1000) NOT NULL,",
        "    displaypath VARCHAR(1000),",
        "    priority INT,",
        "    eventtime TIMESTAMP,",
        "    eventflags INT",
        ");",
        "",
        "CREATE TABLE IF NOT EXISTS alarm_event_data (",
        "    id SERIAL PRIMARY KEY,",
        "    eventid VARCHAR(255) NOT NULL,",
        "    propname VARCHAR(255) NOT NULL,",
        "    propval_str TEXT,",
        "    propval_int BIGINT,",
        "    propval_float DOUBLE PRECISION",
        ");",
        "",
    ])

    return "\n".join(sql_lines)


def generate_mosquitto_conf() -> str:
    """Generate Mosquitto MQTT broker configuration allowing anonymous test connections."""
    return (
        "# Auto-generated Mosquitto MQTT configuration for Ignition Harness\n"
        "listener 1883 0.0.0.0\n"
        "allow_anonymous true\n\n"
        "listener 1885 0.0.0.0\n"
        "allow_anonymous true\n\n"
        "persistence true\n"
        "persistence_location /mosquitto/data/\n"
        "log_dest stdout\n"
    )


def generate_mock_opc_script() -> str:
    """
    Generate Python mock server script for OPC-UA and Rockwell CIP (EtherNet/IP).
    Responds to protocol handshakes so Ignition drivers do not enter immediate FAULT state.
    """
    return '''"""Standalone mock server for OPC-UA binary (ports 4840, 49320, 62541) and Rockwell CIP (port 44818)."""
import asyncio
import struct
import sys
import logging

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
logger = logging.getLogger("SimMockServer")

# OPC-UA Binary HEL/ACK Handshake
# HEL message: MessageType 'HEL' (3 bytes), ChunkType 'F' (1 byte), MessageSize (uint32)
# ACK message: 'ACK' + 'F' + size (28) + version(0) + recvBuf(65535) + sendBuf(65535) + maxMsg(1048576) + maxChunks(100)
OPC_ACK_PACKET = struct.pack("<4sIIIIII", b"ACKF", 28, 0, 65535, 65535, 1048576, 100)

async def handle_opc_client(reader: asyncio.StreamReader, writer: asyncio.StreamWriter, port: int):
    peer = writer.get_extra_info("peername")
    logger.info("OPC-UA connection from %s on port %d", peer, port)
    try:
        while not reader.at_eof():
            try:
                header = await reader.readexactly(8)
            except (asyncio.IncompleteReadError, ConnectionResetError):
                break
            msg_type = header[:4]
            msg_size = struct.unpack("<I", header[4:8])[0]
            # Read remainder of the message
            if msg_size > 8:
                try:
                    remaining = await reader.readexactly(msg_size - 8)
                except (asyncio.IncompleteReadError, ConnectionResetError):
                    break
            if msg_type == b"HELF":
                logger.info("Received OPC-UA HEL packet from %s on port %d, replying with ACK", peer, port)
                writer.write(OPC_ACK_PACKET)
                await writer.drain()
            else:
                # Echo dummy response or acknowledge close
                if msg_type == b"CLOF":
                    break
    except Exception as exc:
        logger.debug("OPC connection error on port %d: %s", port, exc)
    finally:
        writer.close()
        try:
            await writer.wait_closed()
        except Exception:
            pass

# EtherNet/IP CIP Encapsulation Handshake
# Command 0x0065 = RegisterSession
async def handle_cip_client(reader: asyncio.StreamReader, writer: asyncio.StreamWriter):
    peer = writer.get_extra_info("peername")
    logger.info("Rockwell CIP connection from %s on port 44818", peer)
    try:
        while not reader.at_eof():
            try:
                header = await reader.readexactly(24)
            except (asyncio.IncompleteReadError, ConnectionResetError):
                break
            cmd, length, session, status, context, options = struct.unpack("<HHII8sI", header)
            data = b""
            if length > 0:
                try:
                    data = await reader.readexactly(length)
                except (asyncio.IncompleteReadError, ConnectionResetError):
                    break
            if cmd == 0x0065:
                # RegisterSession reply: cmd=0x0065, length=4, session=1, status=0, context, options=0, protocolVersion=1, options=0
                reply_header = struct.pack("<HHII8sI", 0x0065, 4, 1, 0, context, 0)
                reply_body = struct.pack("<HH", 1, 0)
                writer.write(reply_header + reply_body)
                await writer.drain()
            else:
                # Standard success reply for generic encapsulation
                reply_header = struct.pack("<HHII8sI", cmd, 0, session if session else 1, 0, context, 0)
                writer.write(reply_header)
                await writer.drain()
    except Exception as exc:
        logger.debug("CIP error: %s", exc)
    finally:
        writer.close()
        try:
            await writer.wait_closed()
        except Exception:
            pass

async def main():
    servers = []
    # OPC-UA listeners
    for port in [4840, 49320, 62541]:
        srv = await asyncio.start_server(
            lambda r, w, p=port: handle_opc_client(r, w, p),
            "0.0.0.0",
            port,
        )
        servers.append(srv)
        logger.info("Mock OPC-UA server listening on 0.0.0.0:%d", port)

    # Rockwell CIP listener
    cip_srv = await asyncio.start_server(handle_cip_client, "0.0.0.0", 44818)
    servers.append(cip_srv)
    logger.info("Mock Rockwell CIP / Logix server listening on 0.0.0.0:44818")

    async with asyncio.TaskGroup() as tg:
        for s in servers:
            tg.create_task(s.serve_forever())

if __name__ == "__main__":
    try:
        asyncio.run(main())
    except KeyboardInterrupt:
        logger.info("Shutting down mock server.")
'''


def build_sim_compose_dict(
    report: FleetAnalysisReport,
    sim_init_dir: Path,
    output_compose_path: Path,
    database_image: str = "timescale/timescaledb:latest-pg15",
    mailpit_image: str = "axllent/mailpit:latest",
    mosquitto_image: str = "eclipse-mosquitto:2",
    opc_mock_image: str = "python:3.12-slim",
) -> Dict[str, Any]:
    """
    Build Docker Compose dictionary defining the peripheral simulation stack.

    Assigns Docker network aliases for all hostnames discovered across the backups.
    """
    output_dir = output_compose_path.parent.resolve()
    rel_init_dir = format_relative_path(sim_init_dir, output_dir)

    # 1. Database network aliases
    db_aliases = {"timescaledb", "postgres", "db-mock"}
    for host in report.database_hosts:
        db_aliases.add(host.lower())
        if "." in host:
            db_aliases.add(host.split(".")[0].lower())

    # 2. SMTP network aliases
    smtp_aliases = {"mailpit", "smtp-mock"}
    for smtp in report.smtp_servers:
        smtp_aliases.add(smtp.lower())
        if "." in smtp:
            smtp_aliases.add(smtp.split(".")[0].lower())

    # 3. MQTT network aliases
    mqtt_aliases = {"mosquitto", "mqtt-mock"}
    for mqtt in report.mqtt_brokers:
        mqtt_aliases.add(mqtt.lower())
        if "." in mqtt:
            mqtt_aliases.add(mqtt.split(".")[0].lower())

    # 4. OPC-UA / PLC network aliases
    opc_aliases = {"opc-mock", "plc-mock", "kepware"}
    for ep in report.opc_endpoints:
        import re
        m = re.match(r"opc\.tcp://([^:/]+)", ep)
        if m and m.group(1) not in ("localhost", "127.0.0.1"):
            h = m.group(1).lower()
            opc_aliases.add(h)
            if "." in h and not re.match(r"^\d+\.\d+\.\d+\.\d+$", h):
                opc_aliases.add(h.split(".")[0].lower())

    for dev_ip in report.device_targets:
        opc_aliases.add(dev_ip)


    services: Dict[str, Any] = {
        "sim-timescaledb": {
            "image": database_image,
            "container_name": "sim-timescaledb",
            "hostname": "sim-timescaledb",
            "restart": "unless-stopped",
            "environment": {
                "POSTGRES_USER": "postgres",
                "POSTGRES_PASSWORD": "password",
                "POSTGRES_DB": "ignition",
            },
            "ports": ["5432:5432"],
            "volumes": [
                "sim_postgres_data:/var/lib/postgresql/data",
                f"{rel_init_dir}/init-databases.sql:/docker-entrypoint-initdb.d/init-databases.sql:ro",
            ],
            "networks": {
                "ignition_network": {
                    "aliases": sorted(list(db_aliases)),
                }
            },
        },
        "sim-mailpit": {
            "image": mailpit_image,
            "container_name": "sim-mailpit",
            "hostname": "sim-mailpit",
            "restart": "unless-stopped",
            "ports": [
                "1025:1025",
                "8025:8025",
            ],
            "networks": {
                "ignition_network": {
                    "aliases": sorted(list(smtp_aliases)),
                }
            },
        },
        "sim-mosquitto": {
            "image": mosquitto_image,
            "container_name": "sim-mosquitto",
            "hostname": "sim-mosquitto",
            "restart": "unless-stopped",
            "ports": [
                "1883:1883",
                "1885:1885",
            ],
            "volumes": [
                "sim_mosquitto_data:/mosquitto/data",
                f"{rel_init_dir}/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro",
            ],
            "networks": {
                "ignition_network": {
                    "aliases": sorted(list(mqtt_aliases)),
                }
            },
        },
        "sim-opc-plc": {
            "image": opc_mock_image,
            "container_name": "sim-opc-plc",
            "hostname": "sim-opc-plc",
            "restart": "unless-stopped",
            "ports": [
                "4840:4840",
                "49320:49320",
                "62541:62541",
                "44818:44818",
            ],
            "volumes": [
                f"{rel_init_dir}/mock_opc_server.py:/app/mock_opc_server.py:ro",
            ],
            "command": ["python", "/app/mock_opc_server.py"],
            "networks": {
                "ignition_network": {
                    "aliases": sorted(list(opc_aliases)),
                }
            },
        },
    }

    compose_dict: Dict[str, Any] = {
        "services": services,
        "volumes": {
            "sim_postgres_data": None,
            "sim_mosquitto_data": None,
        },
        "networks": {
            "ignition_network": {
                "name": "ignition_network",
                "driver": "bridge",
                "internal": True,
            }
        },
    }

    return compose_dict


def write_simulation_stack(
    report: FleetAnalysisReport,
    output_compose: Path | str = Path("docker-compose.sim.yml"),
    sim_init_dir: Path | str = Path("sim_init"),
) -> Tuple[Path, List[Path]]:
    """
    Write docker-compose.sim.yml and peripheral initialization files.

    Returns (output_compose_path, list_of_generated_files).
    """
    compose_path = Path(output_compose).resolve()
    init_dir = Path(sim_init_dir).resolve()
    init_dir.mkdir(parents=True, exist_ok=True)

    generated_files: List[Path] = []

    # 1. Write init-databases.sql
    sql_content = generate_init_sql(report)
    sql_file = init_dir / "init-databases.sql"
    sql_file.write_text(sql_content, encoding="utf-8")
    generated_files.append(sql_file)

    # 2. Write mosquitto.conf
    mosquitto_content = generate_mosquitto_conf()
    mosquitto_file = init_dir / "mosquitto.conf"
    mosquitto_file.write_text(mosquitto_content, encoding="utf-8")
    generated_files.append(mosquitto_file)

    # 3. Write mock_opc_server.py
    opc_content = generate_mock_opc_script()
    opc_file = init_dir / "mock_opc_server.py"
    opc_file.write_text(opc_content, encoding="utf-8")
    generated_files.append(opc_file)

    # 4. Write docker-compose.sim.yml
    sim_dict = build_sim_compose_dict(report, init_dir, compose_path)
    header = (
        "# Code generated by ignition-gateway-harness peripheral simulation generator.\n"
        "# Source of truth: Backups analysis from ./backups\n"
        "# To spin up simulation services:\n"
        f"#   docker compose -f {compose_path.name} up -d\n\n"
    )
    compose_yaml = header + yaml.dump(
        sim_dict,
        Dumper=CleanYamlDumper,
        sort_keys=False,
        default_flow_style=False,
    )
    compose_path.write_text(compose_yaml, encoding="utf-8")
    generated_files.append(compose_path)

    return compose_path, generated_files


def enrich_fleet_with_discovered_aliases(
    services: List[GatewayServiceConfig],
    report: FleetAnalysisReport,
) -> None:
    """
    Automatically attach discovered production hostnames to GatewayServiceConfig.gan_aliases.

    This ensures that GAN links, redundancy peers, and client connections resolve seamlessly
    within Docker's bridge network without modifying the gateway backups.
    """
    for svc in services:
        discovered = report.gateways.get(svc.service_name)
        if discovered:
            for alias in discovered.hostname_aliases:
                if alias not in svc.gan_aliases:
                    svc.gan_aliases.append(alias)

        # Also check discovered_host_to_service
        for host, matched_svc in report.discovered_host_to_service.items():
            if matched_svc == svc.service_name:
                if host not in svc.gan_aliases:
                    svc.gan_aliases.append(host)
                fqdn = f"{host}.oshkoshglobal.com"
                if fqdn not in svc.gan_aliases:
                    svc.gan_aliases.append(fqdn)


def enrich_fleet_with_isolation_hosts(
    services: List[GatewayServiceConfig],
    report: FleetAnalysisReport,
    blackhole_ip: str = "127.0.0.1",
    redirect_to_sim: bool = False,
) -> None:
    """
    Inject extra_hosts into fleet services for defense-in-depth isolation.

    If redirect_to_sim is True:
        Simulation containers (Mailpit, TimescaleDB, Mosquitto, Mock OPC) catch mocked traffic
        via Docker network aliases on ignition_network.
        All other discovered corporate and external hostnames (e.g. unmocked PLCs, corporate devices,
        intranet endpoints) are blackholed to blackhole_ip (default: 127.0.0.1) in extra_hosts.
    If redirect_to_sim is False (or pure blackhole mode):
        ALL discovered corporate and external hostnames (including SMTP and database relays)
        are blackholed to blackhole_ip (default: 127.0.0.1) in extra_hosts.

    Guarantees that every entry in extra_hosts is a strictly valid IP mapping ('hostname:IP'),
    preventing Docker daemon 'invalid IP address in add-host' failures while ensuring zero outbound leaks.
    """
    if redirect_to_sim:
        import re
        mocked_hosts: set[str] = set()
        for s in report.smtp_servers:
            mocked_hosts.add(s.lower())
            if "." in s:
                mocked_hosts.add(s.split(".")[0].lower())
        for d in report.database_hosts:
            mocked_hosts.add(d.lower())
            if "." in d:
                mocked_hosts.add(d.split(".")[0].lower())
        for m in report.mqtt_brokers:
            mocked_hosts.add(m.lower())
            if "." in m:
                mocked_hosts.add(m.split(".")[0].lower())
        for ep in report.opc_endpoints:
            match = re.match(r"opc\.tcp://([^:/]+)", ep)
            if match and match.group(1).lower() not in ("localhost", "127.0.0.1"):
                h = match.group(1).lower()
                mocked_hosts.add(h)
                if "." in h and not re.match(r"^\d+\.\d+\.\d+\.\d+$", h):
                    mocked_hosts.add(h.split(".")[0].lower())
        for host in report.discovered_host_to_service:
            mocked_hosts.add(host.lower())
            if "." not in host:
                mocked_hosts.add(f"{host.lower()}.oshkoshglobal.com")

        all_hosts = report.get_discovered_corporate_hosts()
        unmocked = [h for h in all_hosts if h not in mocked_hosts]
        extra = [f"{h}:{blackhole_ip}" for h in sorted(unmocked)]
    else:
        extra = report.get_blackhole_extra_hosts(ip=blackhole_ip)

    for svc in services:
        for entry in extra:
            if entry not in svc.extra_hosts:
                svc.extra_hosts.append(entry)

