"""Peripheral Simulation Generator for Ignition Gateway Fleet.

Generates Docker Compose stacks and helper artifacts to simulate production OT/IT
ecosystems around the Ignition fleet without modifying the gateway backups:
- PostgreSQL / TimescaleDB pre-populated with discovered databases, users, and historian tables
- Mailpit SMTP container for alarm notifications
- Mosquitto MQTT broker for Sparkplug B and Cirrus Link modules
- Mock OPC-UA & Rockwell CIP / PLC socket responder
- Network aliases matching all discovered production hostnames
"""

import os
from pathlib import Path
from typing import Any, Dict, List, Optional, Set, Tuple
import yaml

from ignition_gateway_harness.backup_analyzer import FleetAnalysisReport
from ignition_gateway_harness.compose_builder import CleanYamlDumper, format_relative_path
from ignition_gateway_harness.models import GatewayServiceConfig


def generate_init_sql(report: FleetAnalysisReport, db_type: str = "mssql") -> str:
    """Generate SQL initialization script for Microsoft SQL Server 2022 (default) or other supported DBs based on discovered backups."""
    # Discovered databases
    databases: Set[str] = set()
    for db_set in report.database_targets.values():
        databases.update(db_set)

    # Standard fallback databases if none discovered
    default_dbs = {"prod", "mes", "scada", "scada_head", "mes_old", "scada_tagio1", "scada_tagio2", "ignition"}
    databases.update(default_dbs)

    # Discovered users
    users: Set[str] = set()
    for ga in report.gateways.values():
        for db in ga.databases:
            if db.username:
                users.add(db.username.strip())

    if not users:
        users = {"ignition", "defsvcmesdev", "defsvcscadadev", "defsvcprdheadprd"}
    else:
        users.add("ignition")

    if db_type == "mssql":
        sql_lines = [
            "-- Auto-generated by Ignition Gateway Harness Peripheral Simulator",
            "-- Target Database: Microsoft SQL Server 2022",
            "-- Source of truth: Discovered databases and users from gateway backups",
            "USE [master];",
            "GO",
            "",
            "-- 1. Create Discovered Databases with Case-Insensitive Collation",
        ]
        for db_name in sorted(databases):
            clean_db = db_name.lower().replace("-", "_").strip()
            if clean_db and clean_db not in ("master", "tempdb", "model", "msdb"):
                sql_lines.extend([
                    f"IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = N'{clean_db}')",
                    "BEGIN",
                    f"    PRINT 'Creating database [{clean_db}] with collation SQL_Latin1_General_CP1_CI_AS...';",
                    f"    CREATE DATABASE [{clean_db}] COLLATE SQL_Latin1_General_CP1_CI_AS;",
                    f"    ALTER DATABASE [{clean_db}] SET RECOVERY SIMPLE;",
                    "END",
                    "GO",
                    "",
                ])

        sql_lines.extend([
            "-- 2. Configure sa and Application Logins with password",
            "ALTER LOGIN [sa] WITH PASSWORD = N'password', CHECK_POLICY = OFF;",
            "GO",
            "",
        ])
        for u in sorted(users):
            clean_u = u.strip()
            if clean_u and clean_u.lower() not in ("sa", "dbo"):
                sql_lines.extend([
                    f"IF NOT EXISTS (SELECT name FROM sys.server_principals WHERE name = N'{clean_u}')",
                    "BEGIN",
                    f"    PRINT 'Creating server login [{clean_u}]...';",
                    f"    CREATE LOGIN [{clean_u}] WITH PASSWORD = N'password',",
                    "        DEFAULT_DATABASE = [master],",
                    "        CHECK_EXPIRATION = OFF,",
                    "        CHECK_POLICY = OFF;",
                    "END",
                    "ELSE",
                    "BEGIN",
                    f"    ALTER LOGIN [{clean_u}] WITH PASSWORD = N'password',",
                    "        CHECK_EXPIRATION = OFF,",
                    "        CHECK_POLICY = OFF;",
                    "END",
                    "GO",
                    "",
                ])

        sql_lines.extend([
            "-- 3. Map Users and Grant db_owner Privileges Across Discovered Databases",
        ])
        for db_name in sorted(databases):
            clean_db = db_name.lower().replace("-", "_").strip()
            if clean_db and clean_db not in ("master", "tempdb", "model", "msdb"):
                sql_lines.extend([
                    f"USE [{clean_db}];",
                    "GO",
                ])
                for u in sorted(users):
                    clean_u = u.strip()
                    if clean_u and clean_u.lower() not in ("sa", "dbo"):
                        sql_lines.extend([
                            f"IF NOT EXISTS (SELECT name FROM sys.database_principals WHERE name = N'{clean_u}')",
                            "BEGIN",
                            f"    CREATE USER [{clean_u}] FOR LOGIN [{clean_u}];",
                            "END",
                            f"ALTER ROLE [db_owner] ADD MEMBER [{clean_u}];",
                            "GO",
                        ])
                sql_lines.append("")

        sql_lines.extend([
            "-- 4. Standard Ignition Historian, Alarm Journal, and Audit Tables",
        ])
        for db_name in sorted(databases):
            clean_db = db_name.lower().replace("-", "_").strip()
            if clean_db and clean_db not in ("master", "tempdb", "model", "msdb"):
                sql_lines.extend([
                    f"USE [{clean_db}];",
                    "GO",
                    "",
                    "IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = N'sqlth_drv')",
                    "BEGIN",
                    "    CREATE TABLE [dbo].[sqlth_drv] (",
                    "        [id] INT IDENTITY(1,1) PRIMARY KEY,",
                    "        [name] VARCHAR(255) NOT NULL UNIQUE",
                    "    );",
                    "    INSERT INTO [dbo].[sqlth_drv] ([name]) VALUES ('default');",
                    "END",
                    "GO",
                    "",
                    "IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = N'sqlth_tables')",
                    "BEGIN",
                    "    CREATE TABLE [dbo].[sqlth_tables] (",
                    "        [id] INT IDENTITY(1,1) PRIMARY KEY,",
                    "        [tablename] VARCHAR(255) NOT NULL UNIQUE,",
                    "        [drvid] INT FOREIGN KEY REFERENCES [dbo].[sqlth_drv]([id])",
                    "    );",
                    "END",
                    "GO",
                    "",
                    "IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = N'sqlth_te')",
                    "BEGIN",
                    "    CREATE TABLE [dbo].[sqlth_te] (",
                    "        [id] INT IDENTITY(1,1) PRIMARY KEY,",
                    "        [tagid] VARCHAR(500) NOT NULL UNIQUE,",
                    "        [datatype] INT NOT NULL,",
                    "        [querymode] INT NOT NULL",
                    "    );",
                    "END",
                    "GO",
                    "",
                    "IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = N'sqlth_sce')",
                    "BEGIN",
                    "    CREATE TABLE [dbo].[sqlth_sce] (",
                    "        [id] INT IDENTITY(1,1) PRIMARY KEY,",
                    "        [scid] INT NOT NULL,",
                    "        [start_time] BIGINT NOT NULL,",
                    "        [end_time] BIGINT NULL",
                    "    );",
                    "END",
                    "GO",
                    "",
                    "IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = N'alarm_events')",
                    "BEGIN",
                    "    CREATE TABLE [dbo].[alarm_events] (",
                    "        [id] INT IDENTITY(1,1) PRIMARY KEY,",
                    "        [eventid] VARCHAR(255) NOT NULL,",
                    "        [source] VARCHAR(1000) NOT NULL,",
                    "        [displaypath] VARCHAR(1000) NULL,",
                    "        [priority] INT NULL,",
                    "        [eventtime] DATETIME NULL,",
                    "        [eventflags] INT NULL",
                    "    );",
                    "END",
                    "GO",
                    "",
                    "IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = N'alarm_event_data')",
                    "BEGIN",
                    "    CREATE TABLE [dbo].[alarm_event_data] (",
                    "        [id] INT IDENTITY(1,1) PRIMARY KEY,",
                    "        [eventid] VARCHAR(255) NOT NULL,",
                    "        [propname] VARCHAR(255) NOT NULL,",
                    "        [propval_str] NVARCHAR(MAX) NULL,",
                    "        [propval_int] BIGINT NULL,",
                    "        [propval_float] FLOAT NULL",
                    "    );",
                    "END",
                    "GO",
                    "",
                    "IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = N'audit_events')",
                    "BEGIN",
                    "    CREATE TABLE [dbo].[audit_events] (",
                    "        [audit_events_id] INT IDENTITY(1,1) PRIMARY KEY,",
                    "        [event_timestamp] DATETIME NOT NULL DEFAULT GETDATE(),",
                    "        [actor] NVARCHAR(255) NOT NULL,",
                    "        [actor_host] NVARCHAR(255) NULL,",
                    "        [action] NVARCHAR(255) NOT NULL,",
                    "        [action_target] NVARCHAR(255) NULL,",
                    "        [action_value] NVARCHAR(MAX) NULL,",
                    "        [status_code] INT NOT NULL DEFAULT 0",
                    "    );",
                    "END",
                    "GO",
                    "",
                    "IF NOT EXISTS (SELECT * FROM sys.objects WHERE name = N'AUDIT_EVENTS')",
                    "BEGIN",
                    "    CREATE SYNONYM [dbo].[AUDIT_EVENTS] FOR [dbo].[audit_events];",
                    "END",
                    "GO",
                    "",
                ])

        return "\n".join(sql_lines)

    elif db_type == "mysql":
        sql_lines = [
            "-- Auto-generated by Ignition Gateway Harness Peripheral Simulator",
            "-- Target Database: MySQL 8.0",
            "",
        ]
        for db_name in sorted(databases):
            clean_db = db_name.lower().replace("-", "_").strip()
            if clean_db and clean_db not in ("mysql", "information_schema", "performance_schema", "sys"):
                sql_lines.append(f"CREATE DATABASE IF NOT EXISTS `{clean_db}`;")
        for u in sorted(users):
            clean_u = u.strip()
            if clean_u and clean_u.lower() not in ("root",):
                sql_lines.append(f"CREATE USER IF NOT EXISTS '{clean_u}'@'%' IDENTIFIED BY 'password';")
                sql_lines.append(f"ALTER USER '{clean_u}'@'%' IDENTIFIED BY 'password';")
                for db_name in sorted(databases):
                    clean_db = db_name.lower().replace("-", "_").strip()
                    if clean_db and clean_db not in ("mysql", "information_schema", "performance_schema", "sys"):
                        sql_lines.append(f"GRANT ALL PRIVILEGES ON `{clean_db}`.* TO '{clean_u}'@'%';")
        sql_lines.extend([
            "FLUSH PRIVILEGES;",
            "USE `prod`;",
            "CREATE TABLE IF NOT EXISTS `sqlth_drv` (`id` INT AUTO_INCREMENT PRIMARY KEY, `name` VARCHAR(255) NOT NULL UNIQUE);",
            "INSERT IGNORE INTO `sqlth_drv` (`name`) VALUES ('default');",
            "CREATE TABLE IF NOT EXISTS `sqlth_tables` (`id` INT AUTO_INCREMENT PRIMARY KEY, `tablename` VARCHAR(255) NOT NULL UNIQUE, `drvid` INT, FOREIGN KEY (`drvid`) REFERENCES `sqlth_drv`(`id`));",
            "CREATE TABLE IF NOT EXISTS `sqlth_te` (`id` INT AUTO_INCREMENT PRIMARY KEY, `tagid` VARCHAR(500) NOT NULL UNIQUE, `datatype` INT NOT NULL, `querymode` INT NOT NULL);",
            "CREATE TABLE IF NOT EXISTS `sqlth_sce` (`id` INT AUTO_INCREMENT PRIMARY KEY, `scid` INT NOT NULL, `start_time` BIGINT NOT NULL, `end_time` BIGINT NULL);",
            "CREATE TABLE IF NOT EXISTS `alarm_events` (`id` INT AUTO_INCREMENT PRIMARY KEY, `eventid` VARCHAR(255) NOT NULL, `source` VARCHAR(1000) NOT NULL, `displaypath` VARCHAR(1000), `priority` INT, `eventtime` DATETIME, `eventflags` INT);",
            "CREATE TABLE IF NOT EXISTS `alarm_event_data` (`id` INT AUTO_INCREMENT PRIMARY KEY, `eventid` VARCHAR(255) NOT NULL, `propname` VARCHAR(255) NOT NULL, `propval_str` TEXT, `propval_int` BIGINT, `propval_float` DOUBLE);",
            "CREATE TABLE IF NOT EXISTS `audit_events` (`audit_events_id` INT AUTO_INCREMENT PRIMARY KEY, `event_timestamp` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, `actor` VARCHAR(255) NOT NULL, `actor_host` VARCHAR(255) NULL, `action` VARCHAR(255) NOT NULL, `action_target` VARCHAR(255) NULL, `action_value` LONGTEXT NULL, `status_code` INT NOT NULL DEFAULT 0);",
        ])
        return "\n".join(sql_lines)

    else:
        # Fallback to PostgreSQL / TimescaleDB
        sql_lines = [
            "-- Auto-generated by Ignition Gateway Harness Peripheral Simulator",
            "-- Source of truth: Discovered databases and users from gateway backups",
            "",
        ]
        for db_name in sorted(databases):
            clean_db = db_name.lower().replace("-", "_").strip()
            if clean_db and clean_db != "postgres" and clean_db != "template1":
                sql_lines.append(f"SELECT 'CREATE DATABASE {clean_db}' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '{clean_db}')\\gexec")

        user_list = [u.strip() for u in sorted(users) if u.strip() and u.strip().lower() not in ("postgres",)]
        user_list_sql = ", ".join(f"'{u}'" for u in user_list)
        if user_list_sql:
            sql_lines.extend([
                "",
                "-- Discovered user accounts with full privileges across simulated databases",
                "DO $$",
                "DECLARE",
                "    u text;",
                "BEGIN",
                f"    FOR u IN (SELECT unnest(ARRAY[{user_list_sql}]))",
                "    LOOP",
                "        IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = u) THEN",
                "            EXECUTE format('CREATE USER %I WITH PASSWORD %L SUPERUSER CREATEDB', u, 'password');",
                "        END IF;",
                "    END LOOP;",
                "END $$;",
            ])
        sql_lines.extend([
            "",
            "-- Standard Ignition Historian and Alarm Journal tables in default ignition DB",
            "\\c ignition;",
            "",
            "CREATE TABLE IF NOT EXISTS sqlth_drv (",
            "    id SERIAL PRIMARY KEY,",
            "    name VARCHAR(255) NOT NULL UNIQUE",
            ");",
            "INSERT INTO sqlth_drv (name) VALUES ('default') ON CONFLICT DO NOTHING;",
            "",
            "CREATE TABLE IF NOT EXISTS sqlth_tables (",
            "    id SERIAL PRIMARY KEY,",
            "    tablename VARCHAR(255) NOT NULL UNIQUE,",
            "    drvid INT REFERENCES sqlth_drv(id)",
            ");",
            "",
            "CREATE TABLE IF NOT EXISTS sqlth_te (",
            "    id SERIAL PRIMARY KEY,",
            "    tagid VARCHAR(500) NOT NULL UNIQUE,",
            "    datatype INT NOT NULL,",
            "    querymode INT NOT NULL",
            ");",
            "",
            "CREATE TABLE IF NOT EXISTS sqlth_sce (",
            "    id SERIAL PRIMARY KEY,",
            "    scid INT NOT NULL,",
            "    start_time BIGINT NOT NULL,",
            "    end_time BIGINT",
            ");",
            "",
            "CREATE TABLE IF NOT EXISTS alarm_events (",
            "    id SERIAL PRIMARY KEY,",
            "    eventid VARCHAR(255) NOT NULL,",
            "    source VARCHAR(1000) NOT NULL,",
            "    displaypath VARCHAR(1000),",
            "    priority INT,",
            "    eventtime TIMESTAMP,",
            "    eventflags INT",
            ");",
            "",
            "CREATE TABLE IF NOT EXISTS alarm_event_data (",
            "    id SERIAL PRIMARY KEY,",
            "    eventid VARCHAR(255) NOT NULL,",
            "    propname VARCHAR(255) NOT NULL,",
            "    propval_str TEXT,",
            "    propval_int BIGINT,",
            "    propval_float DOUBLE PRECISION",
            ");",
            "",
            "CREATE TABLE IF NOT EXISTS audit_events (",
            "    audit_events_id SERIAL PRIMARY KEY,",
            "    event_timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,",
            "    actor VARCHAR(255) NOT NULL,",
            "    actor_host VARCHAR(255),",
            "    action VARCHAR(255) NOT NULL,",
            "    action_target VARCHAR(255),",
            "    action_value TEXT,",
            "    status_code INT NOT NULL DEFAULT 0",
            ");",
            "",
        ])
        return "\n".join(sql_lines)


def generate_mosquitto_conf() -> str:
    """Generate Mosquitto MQTT broker configuration allowing anonymous test connections."""
    from ignition_gateway_harness.templates import read_template_text
    return read_template_text("mosquitto.conf")


def generate_mock_opc_script() -> str:
    """
    Generate Python mock server script for OPC-UA and Rockwell CIP (EtherNet/IP).
    Responds to protocol handshakes so Ignition drivers do not enter immediate FAULT state.
    """
    from ignition_gateway_harness.templates import read_template_text
    return read_template_text("mock_opc_server.py")



def build_sim_compose_dict(
    report: FleetAnalysisReport,
    sim_init_dir: Path,
    output_compose_path: Path,
    db_type: str = "mssql",
    database_image: Optional[str] = None,
    mailpit_image: str = "axllent/mailpit:latest",
    mosquitto_image: str = "eclipse-mosquitto:2",
    opc_mock_image: str = "python:3.12-slim",
) -> Dict[str, Any]:
    """
    Build Docker Compose dictionary defining the peripheral simulation stack.

    Assigns Docker network aliases for all hostnames discovered across the backups.
    """
    output_dir = output_compose_path.parent.resolve()
    rel_init_dir = format_relative_path(sim_init_dir, output_dir)

    # 1. Database network aliases
    if db_type == "mssql":
        db_aliases = {"mssql", "sqlserver", "db-mock"}
    elif db_type == "mysql":
        db_aliases = {"mysql", "db-mock"}
    else:
        db_aliases = {"timescaledb", "postgres", "db-mock"}

    for host in report.database_hosts:
        db_aliases.add(host.lower())
        if "." in host:
            db_aliases.add(host.split(".")[0].lower())

    # 2. SMTP network aliases
    smtp_aliases = {"mailpit", "smtp-mock"}
    for smtp in report.smtp_servers:
        smtp_aliases.add(smtp.lower())
        if "." in smtp:
            smtp_aliases.add(smtp.split(".")[0].lower())

    # 3. MQTT network aliases
    mqtt_aliases = {"mosquitto", "mqtt-mock"}
    for mqtt in report.mqtt_brokers:
        mqtt_aliases.add(mqtt.lower())
        if "." in mqtt:
            mqtt_aliases.add(mqtt.split(".")[0].lower())

    # 4. OPC-UA / PLC network aliases
    opc_aliases = {"opc-mock", "plc-mock", "kepware"}
    for ep in report.opc_endpoints:
        import re
        m = re.match(r"opc\.tcp://([^:/]+)", ep)
        if m and m.group(1) not in ("localhost", "127.0.0.1"):
            h = m.group(1).lower()
            opc_aliases.add(h)
            if "." in h and not re.match(r"^\d+\.\d+\.\d+\.\d+$", h):
                opc_aliases.add(h.split(".")[0].lower())

    for dev_ip in report.device_targets:
        opc_aliases.add(dev_ip)

    services: Dict[str, Any] = {}

    if db_type == "mssql":
        img = database_image or "mcr.microsoft.com/mssql/server:2022-latest"
        services["sim-mssql"] = {
            "image": img,
            "container_name": "sim-mssql",
            "hostname": "sim-mssql",
            "restart": "unless-stopped",
            "environment": {
                "ACCEPT_EULA": "Y",
                "MSSQL_SA_PASSWORD": "${MSSQL_SA_PASSWORD:-Password123!}",
                "MSSQL_PID": "Developer",
                "MSSQL_COLLATION": "SQL_Latin1_General_CP1_CI_AS",
            },
            "ports": ["1433:1433"],
            "volumes": [
                "sim_mssql_data:/var/opt/mssql",
            ],
            "healthcheck": {
                "test": (
                    "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P \"${MSSQL_SA_PASSWORD:-Password123!}\" -C -Q \"SELECT 1\" || "
                    "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P \"password\" -C -Q \"SELECT 1\" || "
                    "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P \"${MSSQL_SA_PASSWORD:-Password123!}\" -Q \"SELECT 1\" || "
                    "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P \"password\" -Q \"SELECT 1\""
                ),
                "interval": "10s",
                "timeout": "5s",
                "retries": 10,
                "start_period": "15s",
            },
            "networks": {
                "ignition_network": {
                    "aliases": sorted(list(db_aliases)),
                }
            },
        }
        services["sim-db-init"] = {
            "image": img,
            "container_name": "sim-db-init",
            "hostname": "sim-db-init",
            "restart": "no",
            "depends_on": {
                "sim-mssql": {
                    "condition": "service_healthy",
                },
            },
            "volumes": [
                f"{rel_init_dir}/init-databases.sql:/init-databases.sql:ro",
            ],
            "environment": {
                "MSSQL_SA_PASSWORD": "${MSSQL_SA_PASSWORD:-Password123!}",
            },
            "networks": ["ignition_network"],
            "entrypoint": [
                "/bin/bash",
                "-c",
                (
                    "set -e\n"
                    "echo \"[DB-INIT] Executing init-databases.sql against SQL Server instance 'sim-mssql'...\"\n"
                    "if [ -f /opt/mssql-tools18/bin/sqlcmd ]; then\n"
                    "  /opt/mssql-tools18/bin/sqlcmd -S sim-mssql -U sa -P \"$$MSSQL_SA_PASSWORD\" -C -b -i /init-databases.sql || \\\n"
                    "  /opt/mssql-tools18/bin/sqlcmd -S sim-mssql -U sa -P \"password\" -C -b -i /init-databases.sql\n"
                    "else\n"
                    "  /opt/mssql-tools/bin/sqlcmd -S sim-mssql -U sa -P \"$$MSSQL_SA_PASSWORD\" -b -i /init-databases.sql || \\\n"
                    "  /opt/mssql-tools/bin/sqlcmd -S sim-mssql -U sa -P \"password\" -b -i /init-databases.sql\n"
                    "fi\n"
                    "echo \"[DB-INIT] Databases and baseline tables initialized successfully.\"\n"
                ),
            ],
        }
        sim_db_volume = "sim_mssql_data"

    elif db_type == "mysql":
        img = database_image or "mysql:8.0"
        services["sim-mysql"] = {
            "image": img,
            "container_name": "sim-mysql",
            "hostname": "sim-mysql",
            "restart": "unless-stopped",
            "environment": {
                "MYSQL_ROOT_PASSWORD": "password",
                "MYSQL_DATABASE": "prod",
            },
            "ports": ["3306:3306"],
            "volumes": [
                "sim_mysql_data:/var/lib/mysql",
                f"{rel_init_dir}/init-databases.sql:/docker-entrypoint-initdb.d/init-databases.sql:ro",
            ],
            "networks": {
                "ignition_network": {
                    "aliases": sorted(list(db_aliases)),
                }
            },
        }
        sim_db_volume = "sim_mysql_data"

    else:
        img = database_image or "timescale/timescaledb:latest-pg15"
        services["sim-timescaledb"] = {
            "image": img,
            "container_name": "sim-timescaledb",
            "hostname": "sim-timescaledb",
            "restart": "unless-stopped",
            "environment": {
                "POSTGRES_USER": "postgres",
                "POSTGRES_PASSWORD": "password",
                "POSTGRES_DB": "ignition",
            },
            "ports": ["5432:5432"],
            "volumes": [
                "sim_postgres_data:/var/lib/postgresql/data",
                f"{rel_init_dir}/init-databases.sql:/docker-entrypoint-initdb.d/init-databases.sql:ro",
            ],
            "networks": {
                "ignition_network": {
                    "aliases": sorted(list(db_aliases)),
                }
            },
        }
        sim_db_volume = "sim_postgres_data"

    services["sim-mailpit"] = {
        "image": mailpit_image,
        "container_name": "sim-mailpit",
        "hostname": "sim-mailpit",
        "restart": "unless-stopped",
        "ports": [
            "1025:1025",
            "8025:8025",
        ],
        "networks": {
            "ignition_network": {
                "aliases": sorted(list(smtp_aliases)),
            }
        },
    }

    services["sim-mosquitto"] = {
        "image": mosquitto_image,
        "container_name": "sim-mosquitto",
        "hostname": "sim-mosquitto",
        "restart": "unless-stopped",
        "ports": [
            "1883:1883",
            "1885:1885",
        ],
        "volumes": [
            "sim_mosquitto_data:/mosquitto/data",
            f"{rel_init_dir}/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro",
        ],
        "networks": {
            "ignition_network": {
                "aliases": sorted(list(mqtt_aliases)),
            }
        },
    }

    services["sim-opc-plc"] = {
        "image": opc_mock_image,
        "container_name": "sim-opc-plc",
        "hostname": "sim-opc-plc",
        "restart": "unless-stopped",
        "ports": [
            "4840:4840",
            "49320:49320",
            "62541:62541",
            "44818:44818",
        ],
        "volumes": [
            f"{rel_init_dir}/mock_opc_server.py:/app/mock_opc_server.py:ro",
        ],
        "command": ["python", "/app/mock_opc_server.py"],
        "networks": {
            "ignition_network": {
                "aliases": sorted(list(opc_aliases)),
            }
        },
    }

    compose_dict: Dict[str, Any] = {
        "services": services,
        "volumes": {
            sim_db_volume: None,
            "sim_mosquitto_data": None,
        },
        "networks": {
            "ignition_network": {
                "name": "ignition_network",
                "driver": "bridge",
            }
        },
    }

    return compose_dict


def write_simulation_stack(
    report: FleetAnalysisReport,
    output_compose: Path | str = Path("docker-compose.sim.yml"),
    sim_init_dir: Path | str = Path("sim_init"),
    db_type: str = "mssql",
) -> Tuple[Path, List[Path]]:
    """
    Write docker-compose.sim.yml and peripheral initialization files.

    Returns (output_compose_path, list_of_generated_files).
    """
    compose_path = Path(output_compose).resolve()
    init_dir = Path(sim_init_dir).resolve()
    init_dir.mkdir(parents=True, exist_ok=True)

    generated_files: List[Path] = []

    # 1. Write init-databases.sql
    sql_content = generate_init_sql(report, db_type=db_type)
    sql_file = init_dir / "init-databases.sql"
    sql_file.write_text(sql_content, encoding="utf-8")
    generated_files.append(sql_file)

    # 2. Write mosquitto.conf
    mosquitto_content = generate_mosquitto_conf()
    mosquitto_file = init_dir / "mosquitto.conf"
    mosquitto_file.write_text(mosquitto_content, encoding="utf-8")
    generated_files.append(mosquitto_file)

    # 3. Write mock_opc_server.py
    opc_content = generate_mock_opc_script()
    opc_file = init_dir / "mock_opc_server.py"
    opc_file.write_text(opc_content, encoding="utf-8")
    generated_files.append(opc_file)

    # 4. Write docker-compose.sim.yml
    sim_dict = build_sim_compose_dict(report, init_dir, compose_path, db_type=db_type)
    header = (
        "# Peripheral Simulation Stack for Ignition Gateway Fleet\n"
        "# Source of truth: Backups analysis from ./backups\n"
        "# To spin up simulation services:\n"
        f"#   docker compose -f {compose_path.name} up -d\n\n"
    )
    compose_yaml = header + yaml.dump(
        sim_dict,
        Dumper=CleanYamlDumper,
        sort_keys=False,
        default_flow_style=False,
    )
    compose_path.write_text(compose_yaml, encoding="utf-8")
    generated_files.append(compose_path)

    return compose_path, generated_files


def enrich_fleet_with_discovered_aliases(
    services: List[GatewayServiceConfig],
    report: FleetAnalysisReport,
) -> None:
    """
    Automatically attach discovered production hostnames to GatewayServiceConfig.gan_aliases.

    This ensures that GAN links, redundancy peers, and client connections resolve seamlessly
    within Docker's bridge network without modifying the gateway backups.
    """
    for svc in services:
        discovered = report.gateways.get(svc.service_name)
        if discovered:
            for alias in discovered.hostname_aliases:
                if alias not in svc.gan_aliases:
                    svc.gan_aliases.append(alias)

        # Also check discovered_host_to_service
        for host, matched_svc in report.discovered_host_to_service.items():
            if matched_svc == svc.service_name:
                if host not in svc.gan_aliases:
                    svc.gan_aliases.append(host)
                fqdn = f"{host}.oshkoshglobal.com"
                if fqdn not in svc.gan_aliases:
                    svc.gan_aliases.append(fqdn)


def enrich_fleet_with_isolation_hosts(
    services: List[GatewayServiceConfig],
    report: FleetAnalysisReport,
    blackhole_ip: str = "127.0.0.1",
    redirect_to_sim: bool = False,
) -> None:
    """
    Inject extra_hosts into fleet services for defense-in-depth isolation.

    If redirect_to_sim is True:
        Simulation containers (Mailpit, TimescaleDB, Mosquitto, Mock OPC) catch mocked traffic
        via Docker network aliases on ignition_network.
        All other discovered corporate and external hostnames (e.g. unmocked PLCs, corporate devices,
        intranet endpoints) are blackholed to blackhole_ip (default: 127.0.0.1) in extra_hosts.
    If redirect_to_sim is False (or pure blackhole mode):
        ALL discovered corporate and external hostnames (including SMTP and database relays)
        are blackholed to blackhole_ip (default: 127.0.0.1) in extra_hosts.

    Guarantees that every entry in extra_hosts is a strictly valid IP mapping ('hostname:IP'),
    preventing Docker daemon 'invalid IP address in add-host' failures while ensuring zero outbound leaks.
    """
    if redirect_to_sim:
        import re
        mocked_hosts: set[str] = set()
        for s in report.smtp_servers:
            mocked_hosts.add(s.lower())
            if "." in s:
                mocked_hosts.add(s.split(".")[0].lower())
        for d in report.database_hosts:
            mocked_hosts.add(d.lower())
            if "." in d:
                mocked_hosts.add(d.split(".")[0].lower())
        for m in report.mqtt_brokers:
            mocked_hosts.add(m.lower())
            if "." in m:
                mocked_hosts.add(m.split(".")[0].lower())
        for ep in report.opc_endpoints:
            match = re.match(r"opc\.tcp://([^:/]+)", ep)
            if match and match.group(1).lower() not in ("localhost", "127.0.0.1"):
                h = match.group(1).lower()
                mocked_hosts.add(h)
                if "." in h and not re.match(r"^\d+\.\d+\.\d+\.\d+$", h):
                    mocked_hosts.add(h.split(".")[0].lower())
        for host in report.discovered_host_to_service:
            mocked_hosts.add(host.lower())
            if "." not in host:
                mocked_hosts.add(f"{host.lower()}.oshkoshglobal.com")

        all_hosts = report.get_discovered_corporate_hosts()
        unmocked = [h for h in all_hosts if h not in mocked_hosts]
        extra = [f"{h}:{blackhole_ip}" for h in sorted(unmocked)]
    else:
        extra = report.get_blackhole_extra_hosts(ip=blackhole_ip)

    for svc in services:
        for entry in extra:
            if entry not in svc.extra_hosts:
                svc.extra_hosts.append(entry)

