-- Auto-generated by Ignition Gateway Harness Peripheral Simulator
-- Source of truth: Discovered databases and users from gateway backups

SELECT 'CREATE DATABASE ignition' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'ignition')\gexec
SELECT 'CREATE DATABASE mes' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'mes')\gexec
SELECT 'CREATE DATABASE mes_dev' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'mes_dev')\gexec
SELECT 'CREATE DATABASE mes_old' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'mes_old')\gexec
SELECT 'CREATE DATABASE prod' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'prod')\gexec
SELECT 'CREATE DATABASE scada' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'scada')\gexec
SELECT 'CREATE DATABASE scada_head' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'scada_head')\gexec
SELECT 'CREATE DATABASE scada_tagio1' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'scada_tagio1')\gexec
SELECT 'CREATE DATABASE scada_tagio2' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'scada_tagio2')\gexec

-- Discovered user accounts with full privileges across simulated databases
DO $$
DECLARE
    u text;
BEGIN
    FOR u IN (SELECT unnest(ARRAY['defsvcmesdev', 'defsvcmesheadprd', 'defsvcmesheadtst', 'defsvcmestag1prd', 'defsvcmestag1tst', 'defsvcmestag2prd', 'defsvcmestag2tst', 'defsvcprdheadprd', 'defsvcprdheadtst', 'defsvcscadadev', 'defsvcscadaheadprd', 'defsvcscadaheadtst', 'defsvcscadatag1prd', 'defsvcscadatag1tst', 'defsvcscadatag2prd', 'defsvcscadatag2tst']))
    LOOP
        IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = u) THEN
            EXECUTE format('CREATE USER %I WITH PASSWORD %L SUPERUSER CREATEDB', u, 'password');
        END IF;
    END LOOP;
END $$;

-- Standard Ignition Historian and Alarm Journal tables in default ignition DB
\c ignition;

CREATE TABLE IF NOT EXISTS sqlth_drv (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
);
INSERT INTO sqlth_drv (name) VALUES ('default') ON CONFLICT DO NOTHING;

CREATE TABLE IF NOT EXISTS sqlth_tables (
    id SERIAL PRIMARY KEY,
    tablename VARCHAR(255) NOT NULL UNIQUE,
    drvid INT REFERENCES sqlth_drv(id)
);

CREATE TABLE IF NOT EXISTS sqlth_te (
    id SERIAL PRIMARY KEY,
    tagid VARCHAR(500) NOT NULL UNIQUE,
    datatype INT NOT NULL,
    querymode INT NOT NULL
);

CREATE TABLE IF NOT EXISTS sqlth_sce (
    id SERIAL PRIMARY KEY,
    scid INT NOT NULL,
    start_time BIGINT NOT NULL,
    end_time BIGINT
);

CREATE TABLE IF NOT EXISTS alarm_events (
    id SERIAL PRIMARY KEY,
    eventid VARCHAR(255) NOT NULL,
    source VARCHAR(1000) NOT NULL,
    displaypath VARCHAR(1000),
    priority INT,
    eventtime TIMESTAMP,
    eventflags INT
);

CREATE TABLE IF NOT EXISTS alarm_event_data (
    id SERIAL PRIMARY KEY,
    eventid VARCHAR(255) NOT NULL,
    propname VARCHAR(255) NOT NULL,
    propval_str TEXT,
    propval_int BIGINT,
    propval_float DOUBLE PRECISION
);
